name: "pull-request-auto-reviewer"
description: "auto post comments based on changes"
author: pshergie
branding:
  icon: "message-square"
  color: "yellow"
inputs:
  token:
    description: "token for github"
    required: true
  datapath:
    description: "path to data yaml file with comments"
    required: true
  artifacts-path:
    description: "path to PR number, comments and diff"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
